const merge = require('webpack-merge');
const common = require('./webpack.common.js');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = merge(common, {
    mode: 'development',
    devtool: 'cheap-module-eval-source-map',
    plugins: [
        new HtmlWebpackPlugin({
            template: 'src/autogenerated/new_demos.html',
            filename: 'new_demos.html',
        }),
    ],
    devServer: {
        contentBase: './dist',
    },
});
